### PR TITLE
add script to process annotation jsons from COCO and transform them t…

### PR DESCRIPTION
**Pull request by eselkin**
Similar to a cross between transforming the JSONs from COCO to XML as well as the text file creations from create_list.py. Moves the json expectation from create_data.sh to XML format for lmdb creation.

The reason for this creation is the lack of the dev branch with the scripts/batch_spilt_annotation.py file.

### CODE REVIEW

**Review by weiliu89 — APPROVED** [review]
Thanks.

**Comment by pegatest** [comment]
_caffe$ python scripts/Construct_XML_Annotations_from_COCO_JSON.py -y 2014 -t val_ 
Error occurred:
Traceback (most recent call last):
  File "scripts/Construct_XML_Annotations_from_COCO_JSON.py", line 121, in <module>
    E.width(image_file.shape[1]),
AttributeError: 'NoneType' object has no attribute 'shape'

Is there any instruction of using this script? 
Thanks.

**Comment by pegatest** [comment]
Problem Solved, update line 121:
    _image_file = imread(PATH_TO_IMAGES + "COCO_" + str(TYPEPREFIX) + str(YEAR) + "_" + imagename + '.jpg')_

**Comment by Nusrat12** [comment]
/caffe$ ./data/VOC0712/create_list.sh
Create list for VOC2007 trainval...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2012 trainval...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2012/ImageSets/Main/trainval.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
Create list for VOC2007 test...
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/test.txt': No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_label.txt: No such file or directory
sed: can't read /home/tasnim/caffe/data/VOC0712/test_label.txt: No such file or directory
paste: /home/tasnim/caffe/data/VOC0712/test_img.txt: No such file or directory
I0815 20:41:59.816927 12521 get_image_size.cpp:61] A total of 0 images.

How to solve this problem?

**Comment by ranjiewwen** [comment]
> /caffe$ ./data/VOC0712/create_list.sh
> Create list for VOC2007 trainval...
> cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory
> sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
> sed: can't read /home/tasnim/caffe/data/VOC0712/trainval_img.txt: No such file or directory
> cp: cannot stat '/home/tasnim/data/VOCdevkit//VOC2007/ImageSets/Main/trainval.txt': No such file or directory

> How to solve this problem?

i meet the same problem!!!

**Comment by eselkin** [comment]
This script did not touch create_list.sh which was already a part of the repository. Though it seems you're referencing an incorrect directory structure.

**Pull request merged**
